# Note: It requires docker-compose 1.6.0+
#
# Usage: docker-compose up -d
version: '2'

services:
  # soTesty Development Docker
  soride:
    image: sodocker
    privileged: true
    volumes:
      - /dev/bus/usb:/dev/bus/usb
      - /d/WGROCHUL_DESK/soDocker/soDocker/10_TESTS:/headless/Desktop/automation/10_TESTS
      - /d/WGROCHUL_DESK/soDocker/soDocker/20_AUT:/headless/Desktop/automation/20_AUT
      - /d/WGROCHUL_DESK/soDocker/soDocker/30_LIBRARIES:/headless/Desktop/automation/30_LIBRARIES
    environment:
      - CONNECT_TO_GRID=True
    ports:
      - 4723:4723
      - 5901:5901
      - 6901:6901
